### ISSUE TITLE
"S" key unresponsive (pacman).

### ISSUE THREAD

**Issue by Achaean** [fastrgv/CoTerminalApps#2]
"S" key, doesn't seems to do something.
I can't see any alternative colors (and keyboard input remains way delayed).

BTW (not related), what is the difference between Terminal an CoTerminal Apps? :-)

**Comment by fastrgv** [comment]
Only keyboard arrow keys work, but I'm adding the usual wasd as we speak.
Next release will have those.  That was another oversight of mine.
Currently I do not mess with the keyboard delay/repeat settings so perhaps
you can manually set them to make the game playable.  Myself, I have a very
short delay, and a high repeat speed.

Terminal apps is very similar but much easier to compile because it does
not use colored characters.

Also, the documentation is very sparse, I know.  I had to look at procedure
handle_key_down to see what keys are enabled.
Note that the up arrow seems to produce the 'A' character, etc.

**Comment by Achaean** [comment]
Oh, I see!
I'll wait for the next version and I'll try tweaking it.
Bye! :-)
A.
